language: python
python:
    - "2.7"

cache:
  - pip

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  # Install pipenv, and use it to install dev dependencies
  # TODO: Update to only install test dependencies
  - make install

script:
  - make tests
